/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counsellingschedulesystem;
import dao.AppointmentAndRequestsDao;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class CounsellorHome extends javax.swing.JFrame {

    /**
     * Creates new form CounsellorHome
     */
    
    private int counsellorID;
    public CounsellorHome(String name, int counsellorID) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);    
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.counsellorID = counsellorID;
        loadRequestTableData();
        loadAppointmentsTableData(counsellorID);
        lblGreet.setText("Hello, "+ name +"!");
        tblRequests.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblRequests.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblRequests.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblRequests.getColumnModel().getColumn(3).setPreferredWidth(10);
        tblRequests.getColumnModel().getColumn(4).setPreferredWidth(40);
        btnConfirm.setEnabled(false);
        btnComplete.setEnabled(false);
        btnCancel.setEnabled(false);
    }

    public void validateFields(){
        String date = txtDate.getText();
        String reqID = txtRequestID.getText();
        String time = txtTime.getText();
        
        
        if(!date.equals("") && !reqID.equals("") && !time.equals("")){
            btnConfirm.setEnabled(true);
        }
        else{
            btnConfirm.setEnabled(false);
        }
    }
    
    private void loadAppointmentsTableData(int counsellorID) {
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = AppointmentAndRequestsDao.getAppointmentsByCounsellor(counsellorID);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("appointmentID"),
                    rs.getInt("requestID"),
                    rs.getString("userName"),
                    rs.getString("counsellorName"),
                    rs.getString("appointmentDate"),
                    rs.getString("appointmentTime"),
                    rs.getString("status")
            };
            model.addRow(row);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }
    
    public void loadRequestTableData() {
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        model.setRowCount(0); // clear old data

        try {
            ResultSet rs = AppointmentAndRequestsDao.getAllPendingRequests();
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("requestID"),
                    // rs.getInt("userID"),
                    rs.getString("classification"),
                    rs.getString("problemSummary"),
                    rs.getString("status"),
                    rs.getString("requestDate")
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGreet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtRequestID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtAppointmentID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGreet.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGreet.setText("$GREET$");
        getContentPane().add(lblGreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 23, -1, -1));

        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Classification", "Problem Summary", "Status", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequests);
        if (tblRequests.getColumnModel().getColumnCount() > 0) {
            tblRequests.getColumnModel().getColumn(1).setResizable(false);
            tblRequests.getColumnModel().getColumn(2).setResizable(false);
            tblRequests.getColumnModel().getColumn(3).setResizable(false);
            tblRequests.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 411, 1002, 227));

        jLabel1.setText("Input Request ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 526, -1, -1));

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 551, -1, -1));

        txtRequestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequestIDActionPerformed(evt);
            }
        });
        txtRequestID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRequestIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 523, 74, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Your Appointments");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 83, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Requests");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 374, -1, -1));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient Name", "Counsellor Assigned to", "Date", "Time"
            }
        ));
        jScrollPane2.setViewportView(tblAppointments);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 1002, 227));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDateKeyReleased(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 495, 74, -1));

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        txtTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimeKeyReleased(evt);
            }
        });
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 467, 74, -1));

        jLabel4.setText("Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 470, -1, -1));

        jLabel5.setText("Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 498, -1, -1));

        btnComplete.setBackground(new java.awt.Color(51, 255, 51));
        btnComplete.setText("Complete an Appointment");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 202, -1, -1));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel an Appointment");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 231, 172, -1));

        txtAppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentIDActionPerformed(evt);
            }
        });
        txtAppointmentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAppointmentIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1123, 174, 75, -1));

        jLabel6.setText("Appointment ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 177, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgotPassword.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2920, -940, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            String date = txtDate.getText();
            String time = txtTime.getText();
            int requestID = Integer.parseInt(txtRequestID.getText().trim());

            AppointmentAndRequestsDao.confirmRequest(requestID, counsellorID, date, time);
            
            JOptionPane.showMessageDialog(this, "Request confirmed and added to appointments!");
            
            // refresh both tables
            loadRequestTableData();
            loadAppointmentsTableData(counsellorID);
            txtTime.setText("");
            txtDate.setText("");
            txtRequestID.setText("");
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtRequestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequestIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequestIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        try {
            int appointmentID = Integer.parseInt(txtAppointmentID.getText().trim());
            dao.AppointmentAndRequestsDao.completeAppointment(appointmentID);
            JOptionPane.showMessageDialog(this, "Appointment completed successfully!");
            txtAppointmentID.setText("");
            loadRequestTableData();
            loadAppointmentsTableData(counsellorID);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid appointment ID format.");
        } catch (Exception e) {
            if (e.getMessage().contains("No appointment found")) {
                JOptionPane.showMessageDialog(this, "Appointment ID does not exist.");
            } else {
                JOptionPane.showMessageDialog(this, "Error completing appointment: " + e.getMessage());
            }
        e.printStackTrace();
            }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
        int appointmentID = Integer.parseInt(txtAppointmentID.getText().trim());
        
        //cancelAppointment returns user info
        java.util.Map<String, String> userInfo = dao.AppointmentAndRequestsDao.cancelAppointment(appointmentID);

        if (userInfo != null) {
            String userEmail = userInfo.get("email");
            String userName = userInfo.get("name");

            String subject = "Counselling Appointment Cancelled";
            String body = "Hello " + userName + ",\n\n"
                        + "Your counselling appointment (ID: " + appointmentID + ") has been cancelled by your counsellor.\n\n"
                        + "If you have any questions, please contact the counselling office.\n\n"
                        + "Best regards,\n"
                        + "Counselling System";

            dao.EmailSender.sendEmail(userEmail, subject, body);
        }

        JOptionPane.showMessageDialog(this, "Appointment cancelled and user notified!");
        txtAppointmentID.setText("");
        loadRequestTableData();
        loadAppointmentsTableData(counsellorID);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid appointment ID format.");
    } catch (Exception e) {
        if (e.getMessage().contains("No appointment found")) {
            JOptionPane.showMessageDialog(this, "Appointment ID does not exist.");
        } else {
            JOptionPane.showMessageDialog(this, "Error cancelling appointment: " + e.getMessage());
        }
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtAppointmentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppointmentIDKeyReleased
        String ID = txtAppointmentID.getText();

        if(!ID.equals("")){
            btnComplete.setEnabled(true);
            btnCancel.setEnabled(true);
        }
        else{
            btnComplete.setEnabled(false);
            btnCancel.setEnabled(false);
        }
    }//GEN-LAST:event_txtAppointmentIDKeyReleased

    private void txtAppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentIDActionPerformed

    private void txtTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeKeyReleased
        validateFields();
    }//GEN-LAST:event_txtTimeKeyReleased

    private void txtDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyReleased
        validateFields();
    }//GEN-LAST:event_txtDateKeyReleased

    private void txtRequestIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequestIDKeyReleased
        validateFields();
    }//GEN-LAST:event_txtRequestIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounsellorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounsellorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounsellorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounsellorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtRequestID;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
