/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counsellingschedulesystem;
import dao.AppointmentAndRequestsDao;
import java.sql.ResultSet;
import javax.swing.JFrame;
import model.Request;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
private String name;
    /**
     * Creates new form Home
     */
    String[] items = {"Financial Counselling", "Academic Advise", "Mental Health", "Relationship Issues"};
    private Integer currentUserID;
    public Home(String name, Integer currentUserID) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);    
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        btnSubmit.setEnabled(false);
        loadAppointmentsTableData(currentUserID);
        this.currentUserID = currentUserID;
        cmbClassification.setModel(new javax.swing.DefaultComboBoxModel<>(items));        
        lblGreet.setText("Hello, "+ name +"!");
    } 

    private void loadAppointmentsTableData(int currentUserID) {
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = AppointmentAndRequestsDao.getAppointmentsByUser(currentUserID);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("appointmentID"),
                    //rs.getInt("requestID"),
                    rs.getString("userName"),
                    rs.getString("counsellorName"),
                    rs.getString("appointmentDate"),
                    rs.getString("appointmentTime"),
                    rs.getString("status")
            };
            model.addRow(row);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblGreet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbClassification = new javax.swing.JComboBox<>();
        txtProblemSummary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnCancelAppointment = new javax.swing.JButton();
        txtAppointmentID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("HOME PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 15, -1, -1));

        lblGreet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGreet.setText("$GREET$");
        getContentPane().add(lblGreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 91, -1, -1));

        jLabel2.setText("Apply for Counseling");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 145, -1, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 250, -1, -1));

        btnClear.setText("Clear");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 250, -1, -1));

        cmbClassification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClassification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassificationActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClassification, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 179, -1, -1));

        txtProblemSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemSummaryActionPerformed(evt);
            }
        });
        txtProblemSummary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProblemSummaryKeyReleased(evt);
            }
        });
        getContentPane().add(txtProblemSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 213, 372, -1));

        jLabel4.setText("Classification");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 182, -1, -1));

        jLabel5.setText("Problem Summary");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 216, -1, -1));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient Name", "Assigned Counsellor", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 173, 661, 163));

        jLabel3.setText("Your Schedules");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 145, -1, -1));

        btnCancelAppointment.setText("Cancel an Appointment");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 373, -1, -1));

        txtAppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtAppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 342, 47, -1));

        jLabel6.setText("Appointment ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 345, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HOME.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-770, -430, 2070, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClassificationActionPerformed

    private void txtProblemSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemSummaryActionPerformed

    }//GEN-LAST:event_txtProblemSummaryActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Request request = new Request();
        request.setID(Integer.valueOf(currentUserID));
        request.setClassification(cmbClassification.getSelectedItem().toString());
        request.setProblemSummary(txtProblemSummary.getText());
        AppointmentAndRequestsDao.sendRequestAppointment(request);
        txtProblemSummary.setText("");
        JOptionPane.showMessageDialog(null, "Request sent successfully!");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtAppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentIDActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        try {
            int appointmentID = Integer.parseInt(txtAppointmentID.getText().trim());
            dao.AppointmentAndRequestsDao.cancelAppointment(appointmentID);
            JOptionPane.showMessageDialog(this, "Appointment cancelled successfully!");
            txtAppointmentID.setText("");
            loadAppointmentsTableData(currentUserID);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid appointment ID format.");
        } catch (Exception e) {
            if (e.getMessage().contains("No appointment found")) {
                JOptionPane.showMessageDialog(this, "Appointment ID does not exist.");
            } else {
                JOptionPane.showMessageDialog(this, "Error completing appointment: " + e.getMessage());
            }
        e.printStackTrace();
            }
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed

    private void txtProblemSummaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProblemSummaryKeyReleased
        String prob = txtProblemSummary.getText();
        
        if(!prob.equals("")){
            btnSubmit.setEnabled(true);
        }
        else{
            btnSubmit.setEnabled(false);
        }
    }//GEN-LAST:event_txtProblemSummaryKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbClassification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtProblemSummary;
    // End of variables declaration//GEN-END:variables
}
